

[build-system]
requires = ["setuptools>=40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deepseek_vl2"
version = "1.0.0"
description = "DeepSeek-VL2"
authors = [{name = "DeepSeek-AI"}]
license = {file = "LICENSE-CODE"}
urls = {homepage = "https://github.com/deepseek-ai/DeepSeek-VL2"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "transformers==4.38.2",
    "timm>=0.9.16",
    "xformers>=0.0.21",
    "accelerate",
    "sentencepiece",
    "attrdict",
    "einops",
]

[tool.setuptools]
packages = {find = {exclude = ["images"]}}
